// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBchZz25rD7krunkIZgQu92-5_0C5X8GY',
    appId: '1:409328556080:web:d9e0f79d5ea419130335f5',
    messagingSenderId: '409328556080',
    projectId: 'foquita-hiromi-7ea96',
    authDomain: 'foquita-hiromi-7ea96.firebaseapp.com',
    storageBucket: 'foquita-hiromi-7ea96.firebasestorage.app',
    measurementId: 'G-Q8E233BRXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE-itrBc1YQbrhlTGjwC_Q8NxmMFbFT7s',
    appId: '1:409328556080:android:b6e505ba4f4bec060335f5',
    messagingSenderId: '409328556080',
    projectId: 'foquita-hiromi-7ea96',
    storageBucket: 'foquita-hiromi-7ea96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg-vBUFXoR0bSZzSda4jhSnBJJ9zXslRg',
    appId: '1:409328556080:ios:d634ed55b8b2c8900335f5',
    messagingSenderId: '409328556080',
    projectId: 'foquita-hiromi-7ea96',
    storageBucket: 'foquita-hiromi-7ea96.firebasestorage.app',
    iosClientId: '409328556080-4k8oljf5bojbfrgp32j1lef57uvf103p.apps.googleusercontent.com',
    iosBundleId: 'com.hiromi.policode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg-vBUFXoR0bSZzSda4jhSnBJJ9zXslRg',
    appId: '1:409328556080:ios:44411c77835d8a5f0335f5',
    messagingSenderId: '409328556080',
    projectId: 'foquita-hiromi-7ea96',
    storageBucket: 'foquita-hiromi-7ea96.firebasestorage.app',
    iosClientId: '409328556080-91f3gr0nsnfindc35dj3abte669sqv74.apps.googleusercontent.com',
    iosBundleId: 'com.example.policode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBchZz25rD7krunkIZgQu92-5_0C5X8GY',
    appId: '1:409328556080:web:e46eac7aba12ca970335f5',
    messagingSenderId: '409328556080',
    projectId: 'foquita-hiromi-7ea96',
    authDomain: 'foquita-hiromi-7ea96.firebaseapp.com',
    storageBucket: 'foquita-hiromi-7ea96.firebasestorage.app',
    measurementId: 'G-C8B6FLRPP4',
  );

}