// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5brpZW1abtxCeLDK6qhapFXTbw-RQg3w',
    appId: '1:671765559638:web:9577183de295f23394bef7',
    messagingSenderId: '671765559638',
    projectId: 'foquita-hiromi',
    authDomain: 'foquita-hiromi.firebaseapp.com',
    storageBucket: 'foquita-hiromi.firebasestorage.app',
    measurementId: 'G-FDYG99ZEBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgA-_0JzyvefctBd-hH4LOI-aDmVtwKCE',
    appId: '1:671765559638:android:27adc0547eb0950094bef7',
    messagingSenderId: '671765559638',
    projectId: 'foquita-hiromi',
    storageBucket: 'foquita-hiromi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEGL0TUhNpkOS6g3JUGKQOmwp11hIVp6Y',
    appId: '1:671765559638:ios:77326b54bc4823da94bef7',
    messagingSenderId: '671765559638',
    projectId: 'foquita-hiromi',
    storageBucket: 'foquita-hiromi.firebasestorage.app',
    iosBundleId: 'com.example.policode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEGL0TUhNpkOS6g3JUGKQOmwp11hIVp6Y',
    appId: '1:671765559638:ios:77326b54bc4823da94bef7',
    messagingSenderId: '671765559638',
    projectId: 'foquita-hiromi',
    storageBucket: 'foquita-hiromi.firebasestorage.app',
    iosBundleId: 'com.example.policode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5brpZW1abtxCeLDK6qhapFXTbw-RQg3w',
    appId: '1:671765559638:web:0006e941127c7bf294bef7',
    messagingSenderId: '671765559638',
    projectId: 'foquita-hiromi',
    authDomain: 'foquita-hiromi.firebaseapp.com',
    storageBucket: 'foquita-hiromi.firebasestorage.app',
    measurementId: 'G-ERM1TNZRD4',
  );
}
